# layout -- 布局相关
# language: zh-CN
language: zh-CN
## menu 导航菜单显示
menu:
- page: home
  url: /
  icon: 
- page: 前端
  url: /categories/前端/
#   icon: 
- page: 后端
  url: /categories/后端/
#   icon: 
- page: 工具
  url: /categories/工具/
#   icon: 
- page: 资料
  url: /categories/资料/
  icon: 
- page: 关于我
  url: /yang/about.html
  icon: 
## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml


# 各个小工具的设置

## widgets
widgets:
  - search
  # - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: true

## 网站公告设置
# notification: |-
#             <p>主题Snippet v1.2.0版本已经上线！欢迎更新~ <br/>
#             主题下载：<a href="https://github.com/shenliyang/hexo-theme-snippet" title="fork me" target="_blank">Snippet主题</a> <br/>
#             <hr/>接受贡献，包括不限于提交问题与需求，修复代码。欢迎Pull Request。<br/>支持主题：<a href="https://github.com/shenliyang/hexo-theme-snippet/stargazers">Star一下</a>
#             </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/yangcore
 - name: 邮箱
   icon: envelope-o
   href: mailto:943134861@qq.com
 - name: 联系QQ
   icon: qq
   href: tencent://message/?Menu=yes&uin=943134861&Site=80fans&Service=300&sigT=45a1e5847943b64c6ff3990f8a9e644d2b31356cb0b4ac6b24663a3c8dd0f8aa12a545b1714f9d45
 - name: 微博
   icon: weibo
   href: https://weibo.com/u/1783497053
#  - name: QQ群
#    icon: users
#    href: /
#  - name: RSS
#    icon: feed
#    href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1
## 友链设置
links:
  - 公司网站: http://www.paicaifu.com


# 主题自定义个性化配置

## 网站宣传语
branding: 有梦就去追

## 缩略图自定义随机图片
defaultImgs:
  - 

## 截取文章首页描述字数
excerptLength: 120

## 当无分类时显示文字，默认为'无'
noCategoryText: '无'

## 代码高亮配置
highlightTheme: true

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="https://yangcore.github.io/" target="_blank">https://yangcore.github.io/</a>


## 主题评论
### gitment
gitment:
  enable: true
  owner: yangcore
  repo: hexo
  client_id: 90aad1801bc73d1e8810
  client_secret: 7023d8fddf00d5e12519705a787aebf23bb65d4b
  perPage: 10


### 友言评论
uyan:
  enable: false
  uyan_id: 1966422


## 网站访问统计

### 网盟CNZZ统计
cnzz_anaylytics: 1263868967

### 百度统计
baidu_anaylytics: 

### 谷歌统计
google_anaylytics: 

### 百度文章推送
baidu_push:

#网站主题配置
since: 2017
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.0
